version: "3.9"

services:
  # app:
  #   image: node:20-alpine
  #   command: sh -c "yarn install && yarn run dev"
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: <your-password>
  #     MYSQL_DB: todos

  mysql:
    image: mysql:8.4
    # volumes:
    #   - todo-mysql-data:/var/lib/mysql
    container_name: user_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306 


volumes:
  todo-mysql-data: