version: '3.9'

networks:
  users-network:
    driver: bridge

services:
  users-app:
    container_name: simple-user-app
    image: scott207/simple-user-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - users-mysql
      - users-redis
    environment:
      - MYSQL_HOST=users-mysql
      - REDIS_HOST=users-redis
    env_file:
      - ../.env
    networks:
      - users-network

