version: '3.9'
services:
  mysql:
    container_name: users-mysql
    image: "mysql:8.0.33"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./mysql/init_file:/docker-entrypoint-initdb.d
      - ./mysql/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    networks:
      - users-network
  redis:
    container_name: users-redis
    image: redis:7.2.5
    ports:
      - 6379:6379
    networks:
      - users-network
networks:
  users-network:
    driver: bridge
